### PR TITLE
Summernote replacement for obsolete WYSIWYG-editor

### PR DESCRIPTION
**Pull request by sveneberth**
The new HTMLEditor widget replaces the old Wysiwyg Widget. 
The old Editor was sometimes buggy and for e.g. the handling of tables not user friendly.
Now we are using [Summernote](https://github.com/summernote/summernote) to edit texts much easier and get a proper html code.

This editor requires the changes from [#8](https://github.com/viur-framework/server/pull/8). Otherwise styling like the align of images will be cropped.

### CODE REVIEW

**Comment by phorward** [comment]
First bug found!

This happens when the Fieldset containing the new editor widget is collapsed on init:
image

It does not happen when the widget is immediately shown, as it is done when removing the category flag on the bone:
image

I think it has something todo with the width calculation and we have to find a solition for it.

**Comment by phorward** [comment]
Next issue: The slider line on the bottom of the editor has no function. I get a "ns-resize" (↕) icon but can't move it down or up. 

image

**Comment by phorward** [comment]
The new code-view is AWESOME!

But when I switch this view:
image

In code view, I'm getting this:
image

When I then switch back, the editor is resized again to a much lower height:
image

I've tested it also with a non-customized VI version without any custom styles, but looks and works the same.
Edit: I fixed a screenshot and remove an issue which came in due custom styles. The only problem is with the height of the editor on code-view/edit-view switch.

**Comment by phorward** [comment]
It's impossible to insert an image! Just nothing happens. Both tested in Firefox and Chromium.

image

**Review by phorward — CHANGES_REQUESTED** [review]
Hello Sven, in total the new editor runs already very well. Some features are not working, as you can see on the previous comments. Can you correct them soon or take a closer look on it? Are there maybe changes or missing stuff in your local test repository where all works?

**Comment by sveneberth** [comment]
Hello @phorward 
I fixed these issues and now it should works. Can you confirm this?

**Comment by phorward** [comment]
@sveneberth can you please take a look at this issue from @HundiWauWau and correct the styling? It happens on very long lines in the HTML obviously. My CSS-knowledge on this is too bad.

image

**Comment by phorward** [comment]
Hello @sveneberth, 
when testing around in firefox and the new feature/summernote branch, I often recognize that the toolbar is not initialized properly... it is often not drawn, and looks like the following. The interesting thing is, that the toolbar works when hovering over the gray area and the tooltips for the functions are shown. A click activates it. There is no way to make the toolbar visible. Can you please check this out?
I can reproduce it on two different computers, but it sometimes works and sometimes it does not work.

screenshot_2019-02-06 viur administation

**Review by phorward — APPROVED** [review]

**Pull request merged**
